### ISSUE TITLE
Master is not merged into the companion pr before building

### ISSUE THREAD

**Issue by bkchr** [paritytech/pipeline-scripts#10]
The old script merged the latest master into the companion branch (but only locally in the pipeline) before running the tests. We still merge substrate master into the pr branch (also locally in the pipeline) and this can break the compilation.

**Comment by TriplEight** [comment]
Do I get it right: the problem is that substrate's PR merges master during the companion job and others don't?

**Comment by bkchr** [comment]
Yes

**Comment by azerella** [comment]
Sorry, I'm still not following the issue here...Are we saying we _no longer_ want to merge master into the companion branch entirely?

Is this just for substrate PR merges or _all_ merges?

**Comment by bkchr** [comment]
No, we currently don't merge master into the companion branch. This is a problem.

So, for example, we are checking out the polkadot branch and should polkadot master into this branch.
