### ISSUE TITLE
Check Runtime Migration job fails for PRs with companions 

### ISSUE THREAD

**Issue by muharem** [paritytech/pipeline-scripts#104]
`check-runtime-migration-*` CI jobs fail when companion PRs provided.
The CI job extends the `.check-dependent-project` job.
The script reports that it can not update the Cargo.lock file since the cargo command run with `--locked` arg.
For the companion PRs we usually do not commit the Cargo.* files, since they usually contain local machine specific artifacts (from diener tool).

PR example with failing CI jobs:
https://github.com/paritytech/substrate/pull/14434

Failed CI job example: 
https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/3296674

**Comment by mordamax** [comment]
@muharem I didn't know about these CI jobs tbh. now I see that they've been recently added by @liamaharon & @alvicsam  here https://github.com/paritytech/substrate/pull/14618/files

@liamaharon @alvicsam could you follow up on this issue, please?

**Comment by liamaharon** [comment]
I think we need to remove `--locked` from the runtime migration `COMPANION_CHECK_COMMAND` command? It doesn't seem to be used in the `check-dependent-polkadot` which I modelled the new CI job after.

@muharem you can ignore the jobs in your PR for now, and I'll open a PR to remove --locked.

**Comment by liamaharon** [comment]
@muharem can you check if the fix in this PR resolves your issue? https://github.com/paritytech/substrate/pull/14690
