### ISSUE TITLE
Feature request: run short benchmarks

### ISSUE THREAD

**Issue by alvicsam** [paritytech/pipeline-scripts#27]
Recently short benchmarks were added to the Polkadot pipeline: https://github.com/paritytech/polkadot/pull/5188

It would be nice to run them when there are changes in Substrate to check that they are not broken

Part of https://github.com/paritytech/ci_cd/issues/353

**Comment by joao-paulo-parity** [comment]
so it's https://github.com/paritytech/polkadot/blob/634520cd3cf4b2b850db807daaaa32e480099981/.gitlab-ci.yml#L825? but first we'd have to build the CLI https://github.com/paritytech/polkadot/blob/634520cd3cf4b2b850db807daaaa32e480099981/.gitlab-ci.yml#L626?

it seems easy to implement this feature

**Comment by alvicsam** [comment]
Yes, that's correct
