### ISSUE TITLE
Allow companion branches to be conditionally customizable

### ISSUE THREAD

**Issue by joao-paulo-parity** [paritytech/pipeline-scripts#32]
For the use-case of https://github.com/paritytech/substrate/pull/11276 where a PR is **not targetting master**, we can allow a syntax for specifying which branch should be used for the checks

Thus instead of

```
polkadot companion: pr
```

One would be able to say in the PR description

```
polkadot companion branch: [something]
```

**Comment by chevdor** [comment]
This is if you want to modify the companion system to be used in non-companion use cases.
I am happy to have any solution for now though.

Ultimately, we may want a separate workflow for the release process where the CI could make educated guesses based on our naming conventions and allow override as needed.

Here is for instance how branches are named for a standard release:
- substrate: `polkadot-v0.9.20`
- polkadot: `release-v0.9.20`
- cumulus: `release-parachains-v9.0.0`

it is important that we may need some flexibility on naming for emergency releases for instance. I think it would be fine to let the CI fail on the best guesses and have a way to tell the CI to switch the checks to another branch.

**Comment by joao-paulo-parity** [comment]
> Here is for instance how branches are named for a standard release:
> * substrate: `polkadot-v0.9.20`
> * polkadot: `release-v0.9.20`
> * cumulus: `release-parachains-v9.0.0`

@chevdor I was able to correlate `polkadot-v0.9.20` on Substrate to Polkadot's `release-v0.9.20` (https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/1521543#L95) by extracting the suffix, as you'll be able to see here: https://github.com/paritytech/substrate/blob/7e2b168e435df65c8b35da13b5e330300d74b921/.gitlab-ci.yml#L165 (suffix in this case is the `*`).

However, the Cumulus one is more complicated since the suffixes don't match 1-to-1. Would it be possible to have the same `v0.9.20` suffix for all repositories?

**Comment by chevdor** [comment]
Unfortuately no and it will not get better, one of the reason is that we will be splitting (it started on cumulus) runtime and client relesses so we may have different branches. Also the versions numbers are not in sync (on purpose) and will be more and more disconnected.
