### ISSUE TITLE
check_dependent_project: retrigger once the PR description changes

### ISSUE THREAD

**Issue by joao-paulo-parity** [paritytech/pipeline-scripts#37]
Problem: https://github.com/paritytech/substrate/pull/11148/#issue-1188679845 was edited around 10 hours ago to no longer have a Cumulus companion

![image](https://user-images.githubusercontent.com/77391175/167006064-c52ab35e-929d-4f8f-91eb-7471e96f7271.png)

When that happened, however, the [`check-dependent-cumulus` job](https://github.com/paritytech/substrate/blob/06d43cba9c2498d058a600dfe200c75e36d1181f/.gitlab-ci.yml#L504) was not run again.

Solution: Run the `check-dependent-*` jobs once the PR description changes. This is justified because edits to the PR's description might change its dependency chain, which matters for those jobs.

**Comment by mutantcornholio** [comment]
> edits to the PR's description might change its dependency chain, which matters for those jobs.

Could you please elaborate on how this works?

**Comment by mutantcornholio** [comment]
Ah, okay, [this is it](https://github.com/paritytech/parity-processbot/issues/384), right?

**Comment by joao-paulo-parity** [comment]
it's referring to https://github.com/paritytech/pipeline-scripts#step-2-detect-all-dependents and subsequent steps

**Comment by mordamax** [comment]
@joao-paulo-parity if there were 2 companions, and vanity-service added 2 red (failed) statuses. Then you remove one companion, and we re-triggered check_dependent_project - will the other status be automatically removed or ignored somehow? 
let me know if it's not clear :) not sure if I explained it enough

**Comment by joao-paulo-parity** [comment]
> will the other status be automatically removed or ignored somehow?

Naively, all companion checks should be retried since companions might be related to each other. e.g. if a PR has both Polkadot and Cumulus companions and I remove the Polkadot one, the Cumulus check should be rerun because the Polkadot companion matters for it.

Optimally, we could have a smart script that can detect precisely which checks should be rerun based on what changed.

I don't think it's necessary for us to go for the optimized version *right now* since description edits shouldn't happen often; it's better to have something suboptimal in the short term rather than a complete lack of the feature.
