### ISSUE TITLE
bench-bot: enable for cumulus

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/pipeline-scripts#50]
make it work

**Comment by joao-paulo-parity** [comment]
OpsTooling needs to know which flags exactly apply for Cumulus. It's set up Substrate (https://github.com/paritytech/pipeline-scripts/blob/294a98d4fbdbc2daf38b4d5e8da89735a7cb7d53/bench-bot.sh#L44) and Polkadot (https://github.com/paritytech/pipeline-scripts/blob/294a98d4fbdbc2daf38b4d5e8da89735a7cb7d53/bench-bot.sh#L67) already.

**Comment by joao-paulo-parity** [comment]
blocked by https://github.com/paritytech/internal_it/issues/118

**Comment by alvicsam** [comment]
I have a question. Recently we had a [request](https://github.com/paritytech/ci_cd/issues/468) to publish benchmark results to S3. It'll work only for `release-parachain-v*` branches. Should it also work for other branches/tags?
