### ISSUE TITLE
check_dependent_project: handle companion PR changes

### ISSUE THREAD

**Issue by joao-paulo-parity** [paritytech/pipeline-scripts#62]
Problem: suppose the usual scenario of a Substrate PR with a Polkadot companion PR. Since the check is on Substrate's pipeline, it will rerun when commits are pushed to the Substrate PR, but not when commits are pushed to the Polkadot PR. The same is true for description changes.

Solution: trigger the `check-dependent-*` jobs when **any** PR in the dependency chain incurs changes to their description or commits, not only the PR where the change happened.

For this we'll need to have some database for storing and querying the connections - that is, dependencies and dependents - for a given PR. Since connections are parsed from PRs' descriptions, we'll need to react to description changes (#37) which can be done through a GitHub Action or App. For the database we could try to leverage the CI/CD Redis instance (https://github.com/paritytech/ci_cd/wiki/GitLab:-Redis-for-GitLab-CI).

**Comment by mordamax** [comment]
I'd hesitate to iterate this through pipeline-scripts .sh file with 1,2k lines of code. The CBS should be refactored at the right scale level, so it may include this kind of feature

This will be included in the design of the new CBS

<img width="1110" alt="image" src="https://user-images.githubusercontent.com/1177472/187423314-f194c297-ec78-4e4f-94fd-ed8eaf15b99f.png">
