### ISSUE TITLE
bench-bot: example commands

### ISSUE THREAD

**Issue by joao-paulo-parity** [paritytech/pipeline-scripts#63]
# bench-bot

## Substrate

 `/cmd queue -c bench-bot $ pallet runtime pallet_name`

Example:

`/cmd queue -c bench-bot $ pallet dev pallet_contracts`

### Pallet

`/cmd queue -c bench-bot $ pallet runtime pallet_name`

Example:

`/cmd queue -c bench-bot $ pallet westend-dev pallet_balances`

### XCM

`/cmd queue -c bench-bot $ xcm runtime pallet_name`

Example:

`/cmd queue -c bench-bot $ xcm westend-dev pallet_balances`

## Cumulus

Note:  The `chain_type` argument in the following commands can be one of the folders inside of `parachains/runtimes`, i.e. as of this writing `assets`, `testing`, `testing` and `contracts`.

### Pallet

`/cmd queue -c bench-bot $ pallet runtime chain_type pallet_name`

Example:

`/cmd queue -c bench-bot $ pallet statemine assets pallet_xcm_benchmarks::generic`

### XCM

`/cmd queue -c bench-bot $ xcm runtime chain_type pallet_name`

Example:

`/cmd queue -c bench-bot $ xcm statemine assets pallet_xcm_benchmarks::generic`

---

To patch some external branch into the command's branch before running, use the syntax `-v PATCH_[repository]=[PR_NUMBER | BRANCH]`. This syntax can be used multiple times in case you need to use multiple branches. Examples:

- Patch Substrate PR number 11756 into the command's branch
  -  `/cmd queue -v PATCH_substrate=11756 -c bench-bot $ [...args]`
- Patch Substrate branch  `next` into the command's branch
  - `/cmd queue -v PATCH_substrate=next -c bench-bot $ [...args]`

**Comment by joao-paulo-parity** [comment]
Added example for patching feature (https://github.com/paritytech/pipeline-scripts/issues/41)

**Comment by joao-paulo-parity** [comment]
Updated command syntax for Cumulus (#67)

**Comment by muharem** [comment]
Docs on pull request commands and queue commend
https://github.com/paritytech/command-bot#pull-request-commands-
